#配置日志
logging:
  file: /dataFile/yhsmy/logs/yhsmy.log
  level:
    com.yhsmy: debug

#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.187.65:3306/yhsmy?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: Lzy900215@
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    asyncInit: true
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-session-name: admin
        principal-cookie-name: admin
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin

  #配置redis
  redis:
    host: 118.25.187.65
    password: Lzy900215@
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 0
        max-wait: 10000ms


  # 整合rabbitMq
  rabbitmq:
    host: 118.25.187.65
    port: 5672
    username: lizy
    password: lzy900215
    virtual-host: smy
    publisher-confirms: true
    publisher-returns: true

    #配置邮箱
  mail:
    default-encoding: UTF-8
    host: smtp.mxhichina.com
    username: lizy@yhsmy.com
    password: Lzy900215@
    from: ${spring.mail.username}

# 配置fastdfs
fdfs:
  connect-timeout: 601
  so-timeout: 1501
  thumb-image:
    width: 150
    height: 150
  web-server-url: 118.25.187.65:8400
  tracker-list:
  - 172.17.0.16:22122
  - 118.25.187.65:22122
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
    max_idle_per_key: 5

#整合微信
wx:
  appId: wx78c97398886ecc72
  appSecret: b43ec1253ca937c055d1e5ae240f5ca3
  token: $yhsmy$ #微信公众号的token
  wechatPrifix: https://api.weixin.qq.com/ #微信公众号的前缀部分
  wechatMiddlePart: cgi-bin/ #微信公众号URL的中间部分
  robot: http://api.qingyunke.com/api.php?key=free&appid=0&msg= #青云客聊天机器人qingyunke