server:
  port: 8900
#  ssl:
#    key-store: classpath:3439323_erp.yhsmy.com.pfx
#    key-store-password: 2Cd464GW
#    key-store-type: PKCS12
    #key-alias: erp.yhsmy.com

# 激活环境
spring:
  profiles:
    active: prod #active: dev
  servlet:
    multipart:
      max-file-size: 5MB #单个文件的最大值
      max-request-size: 50MB # 上传文件总的最大值
      enabled: true

  # freemarker配置
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

#配置mybatis
mybatis:
  type-aliases-package: com.yhsmy.entity.vo.*
  mapper-locations: classpath*:com/yhsmy/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法自动转换



